kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  generateName: pvc-blue-
  annotations:
    volume.beta.kubernetes.io/storage-class: "blue"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
