kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  generateName: pvc-gold-
  annotations:
    volume.beta.kubernetes.io/storage-class: "gold"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
