kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  generateName: pvc-orange-
  annotations:
    volume.beta.kubernetes.io/storage-class: "orange"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
