kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  generateName: pvc-silver-
  annotations:
    volume.beta.kubernetes.io/storage-class: "silver"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
